# Target Accrual Redemption Forward (TARF) Global KO

This notebook demonstrates how to access and use the functionalities of **Target Accrual Redemption Forward (TARF)** which are part of our **QPS** module within LSEG Financial Analytics SDK.

**You will be able to:**
* Define TARF instrument with basic parameters
* Configure pricing parameters
* Evaluate TARF Analytics

TARF Global KO - This is a variant of a regular TARF (possibly with an EKI on the OTM side), where there is also a KO barrier.

The barrier AFFECTS ALL CASH-FLOWS (i.e. both on the ITM and the OTM side of the deal). The observation of the barrier can be continuous (American barrier) or discrete (on fixing dates). If the KO barrier is triggered, future profits and losses for the holder are KO, but any previous profit and loss is maintained. Triggering the KO barrier redeems the instrument, as it cannot generate any future cashflow.

As for any TARF, if the profit target is reached (before KO is triggered), the instrument redeems. There may be a 'racing' condition when in a certain time step both the KO has been triggered and the target has been reached. It is assumed that the KO would prevail and no cash-flows are generated for such period (nor for any future period). So, either way, the TARF is redeemed.

## Imports

Import the following necessary modules:

- `lseg_analytics.instruments.structured_products` - for Structured Products instruments definitions and analytics

In [1]:
from lseg_analytics.instruments import structured_products as sp

import json
import datetime as dt
import pandas as pd
from IPython.display import display

## Data Preparation

To define a Structured Product instrument, in this example barrier TARF, you need to follow a structured 3-step process:
* **Structured Product Definition** - Specify basic Structured Product parameters (strike, dates, notional, index)
* **Structured Product Instrument Definition** - Create the instrument object
* **Pricing Preferences** - Configure pricing parameters, optional

In [2]:
# 1. Create SP definition object

TARF_definition = sp.StructuredProductsDefinition(
    deal_ccy = "EUR",
    instrument_tag = "TARF_Global_KO",
    inputs = [
        sp.NameTypeValue(name="Underlying", type = "string", value="USDEUR"),
        sp.NameTypeValue(name="StartDate", type = "date", value= dt.date(2022, 1, 25)),
        sp.NameTypeValue(name="EndDate", type = "string", value="StartDate + 1Y"),
        sp.NameTypeValue(name="Frequency", type = "string", value="2M"),
        sp.NameTypeValue(name="Notional", type = "string", value="100000"),
        sp.NameTypeValue(name="Strike", type = "string", value="0.85"),
        sp.NameTypeValue(name="KnockOutRate", type = "string", value="1.02"),
        sp.NameTypeValue(name="IsKnockOutEvent", type = "string", value="FX[t] >= KnockOutRate"),
        sp.NameTypeValue(name="IsRedemptionEvent", type = "string", value="Sum[t] >= ProfitTarget"),
        sp.NameTypeValue(name="ProfitTarget", type = "string", value="20%"),
        sp.NameTypeValue(name="KO_Payment", type = "string", value="Settlement[t]"),
    ],
    payoff_description = [
					[
                        "Schedule Type",
                        "Schedule description",
                        "FX",
                        "Coupon",
                        "Settlement",
                        "Sum",
                        "Alive",
                        "KO_Amount",
                        "Price"
                    ],
                    [
                        "AtDate",
                        "StartDate",
                        "",
                        "",
                        "0",
                        "",
                        "IF(ProfitTarget >= 0, 1, 0)",
                        "",
                        ""
                    ],
                    [
                        "OnSchedule",
                        "DateTable(StartDate + Frequency, EndDate, Frequency, ResetGap := 0b)",
                        "FxSpot(Underlying)",
                        "IF(IsKnockOutEvent, 0, FX[t] - Strike)",
                        "Coupon[t] * Notional",
                        "Sum[LastDate] + max(Coupon[t],0)",
                        "If(IsRedemptionEvent or IsKnockOutEvent, 0, Alive[LastDate-1])",
                        "Alive[LastDate-1] * (1-Alive[LastDate]) * KO_Payment",
                        "Receive (Alive[t] * Settlement[t] + KO_Amount[t])"
                    ],
                    [
                        "AtDate",
                        "EndDate",
                        "FxSpot(Underlying)",
                        "IF(IsKnockOutEvent, 0, FX[t] - Strike)",
                        "Coupon[t] * Notional",
                        "Sum[LastDate] + max(Coupon[t],0)",
                        "If(IsRedemptionEvent or IsKnockOutEvent, 0, Alive[LastDate-1])",
                        "Alive[LastDate-1] * (1-Alive[LastDate]) * KO_Payment",
                        "Receive (Alive[t] * Settlement[t] + KO_Amount[t])"
                    ]
				]
)


# 2. Create SP instrument definition object

tarf_global_ko = sp.StructuredProductsDefinitionInstrument(definition = TARF_definition)
print("Instrument definition created")


# 3. Create SP parameters object - optional

TARF_pricing_params = sp.StructuredProductsPricingParameters(
    valuation_date= dt.date(2022, 3, 16),  # Set your desired valuation date
    numerical_method = sp.GenericNumericalMethod(method="MonteCarlo"),
    models=[sp.ModelDefinition(
            underlying_code = "USDEUR",
            underlying_tag = "USDEUR",
            underlying_currency = "EUR",
            asset_class = "ForeignExchange",
            model_name= "Heston")]
)
print("Pricing parameters configured")

Instrument definition created
Pricing parameters configured

## Request Execution

In [3]:
# Execute the calculation using the price() function
# The 'definitions' parameter accepts a list of instruments definitions for batch processing

response = sp.price(
    definitions=[tarf_global_ko],
    pricing_preferences=TARF_pricing_params,
    market_data=None,
    return_market_data=True,  # or False
    fields=None  # or specify fields as a string
)

print("Pricing execution completed")

Pricing execution completed

## Results Display

#### Key Sections in the `response` JSON

 - **definitions**: Instrument setup (e.g., strike, dates, notional, underlying, barrier, profit target), it's StructuredProductDefinition that we used. 

 - **pricingPreferences**: Valuation date, financial model, numerical method.

 - **analytics**:
   - **tabularData**: `data`, `headers`, `statuses`
   - **cashflows**: Includes arrays and detailed `cashFlows` (payments, fixings)
   - **description**: Instrument summary StructuredProductDefinition and also the default fields not specified in the StructuredProductDefinition, but used by default in the calculation
   - **greeks**: Sensitivities like `deltaAmountInDealCcy`, `gammaAmountInDealCcy`, `thetaAmountInDealCcy`, `vegaAmountInDealCcy`
   - **pricingAnalysis**: `valuationDate`, `marketDataDate`
   - **valuation**: `marketValueInDealCcy`
   - **error**: Empty if no issues

#### Description
Useful for understanding which fields are included by default in the price function, even if they are not explicitly specified.

In [4]:
# Extract description from response
description = response.data.analytics[0].description

# Convert to dictionary for display
print(json.dumps(description.as_dict(), indent=4))

{
    "instrumentTag": "TARF_Global_KO",
    "dealCcy": "EUR",
    "discountCurveId": "IRCurve_EUREURIBORSwapZCCurve_0001-01-01T00:00:00",
    "discountCurveName": "EUR EURIBOR Swap ZC Curve",
    "outputList": {
        "Alive": 3.825060458,
        "Coupon": 0.259127038,
        "FX": 5.408588413,
        "KO_Amount": 4574.657197208,
        "Price": 17165.414122093,
        "Settlement": 25912.703846373,
        "Sum": 1.066484853
    },
    "processingInformation": "'PricePercent' column was not retrieved in payoff description: related fields will not be retrieved. The following greeks could not be retrieved: Theta, Vega, Gamma, Delta. Make sure a 'PricePercent' column is specified in payoff description to compute greeks. "
}

#### Analytics

##### Valuation

In [5]:
# Extract vauation from the response
valuation = response.data.analytics[0].valuation

# Convert the dictionary to a DataFrame
df_tarf_valuation = pd.DataFrame(list(valuation.items()), columns=["Field", "Value"])

display(df_tarf_valuation)

                  Field         Value
0  marketValueInDealCcy  17165.414122

##### Cash Flows

In [6]:
# Extract cashflows from response
cashflows = response.data.analytics[0].cashflows["cashFlows"]

# Build dataframes for all cash flow types
df_fx = pd.DataFrame(cashflows[0]['payments']).rename(columns={'amount': cashflows[0]['legTag']})
df_coupon = pd.DataFrame(cashflows[1]['payments']).rename(columns={'amount': cashflows[1]['legTag']})
df_settlement = pd.DataFrame(cashflows[2]['payments']).rename(columns={'amount': cashflows[2]['legTag']})
df_sum  = pd.DataFrame(cashflows[3]['payments']).rename(columns={'amount': cashflows[3]['legTag']})
df_alive = pd.DataFrame(cashflows[4]['payments']).rename(columns={'amount': cashflows[4]['legTag']})
df_ko_amount = pd.DataFrame(cashflows[5]['payments']).rename(columns={'amount': cashflows[5]['legTag']})
df_price = pd.DataFrame(cashflows[6]['payments']).rename(columns={'amount': cashflows[6]['legTag']})

display(df_fx)
display(df_coupon)
display(df_settlement)
display(df_sum)
display(df_alive)
display(df_ko_amount)
display(df_price)

         date  discountFactor        FX currency   event   occurence
0  2022-01-25        0.000000  0.000000      EUR  Payoff  Historical
1  2022-03-25        1.000123  0.906117      EUR  Payoff      Future
2  2022-05-25        1.001116  0.904112      EUR  Payoff      Future
3  2022-07-25        1.002044  0.901621      EUR  Payoff      Future
4  2022-09-26        1.002831  0.898307      EUR  Payoff      Future
5  2022-11-25        1.003338  0.895248      EUR  Payoff      Future
6  2023-01-25        1.003616  0.891465      EUR  Payoff      Future

         date  discountFactor    Coupon currency   event   occurence
0  2022-01-25        0.000000  0.000000      EUR  Payoff  Historical
1  2022-03-25        1.000123  0.056117      EUR  Payoff      Future
2  2022-05-25        1.001116  0.051360      EUR  Payoff      Future
3  2022-07-25        1.002044  0.045418      EUR  Payoff      Future
4  2022-09-26        1.002831  0.040400      EUR  Payoff      Future
5  2022-11-25        1.003338  0.035367      EUR  Payoff      Future
6  2023-01-25        1.003616  0.029967      EUR  Payoff      Future

         date  discountFactor   Settlement currency   event   occurence
0  2022-01-25        0.000000     0.000000      EUR  Payoff  Historical
1  2022-03-25        1.000123  5611.745667      EUR  Payoff      Future
2  2022-05-25        1.001116  5136.040150      EUR  Payoff      Future
3  2022-07-25        1.002044  4541.756301      EUR  Payoff      Future
4  2022-09-26        1.002831  4039.973126      EUR  Payoff      Future
5  2022-11-25        1.003338  3536.692943      EUR  Payoff      Future
6  2023-01-25        1.003616  2996.714666      EUR  Payoff      Future

         date  discountFactor       Sum currency   event   occurence
0  2022-01-25        0.000000  0.000000      EUR  Payoff  Historical
1  2022-03-25        1.000123  0.056117      EUR  Payoff      Future
2  2022-05-25        1.001116  0.109251      EUR  Payoff      Future
3  2022-07-25        1.002044  0.158435      EUR  Payoff      Future
4  2022-09-26        1.002831  0.204555      EUR  Payoff      Future
5  2022-11-25        1.003338  0.247751      EUR  Payoff      Future
6  2023-01-25        1.003616  0.287477      EUR  Payoff      Future

         date  discountFactor   Alive currency   event   occurence
0  2022-01-25        1.000000  1.0000      EUR  Payoff  Historical
1  2022-03-25        1.000123  1.0000      EUR  Payoff      Future
2  2022-05-25        1.001116  0.9662      EUR  Payoff      Future
3  2022-07-25        1.002044  0.7392      EUR  Payoff      Future
4  2022-09-26        1.002831  0.4866      EUR  Payoff      Future
5  2022-11-25        1.003338  0.3428      EUR  Payoff      Future
6  2023-01-25        1.003616  0.2840      EUR  Payoff      Future

         date  discountFactor    KO_Amount currency   event   occurence
0  2022-01-25        0.000000     0.000000      EUR  Payoff  Historical
1  2022-03-25        0.000000     0.000000      EUR  Payoff      Future
2  2022-05-25        1.001116   292.999264      EUR  Payoff      Future
3  2022-07-25        1.002044  1913.796582      EUR  Payoff      Future
4  2022-09-26        1.002831  1506.945898      EUR  Payoff      Future
5  2022-11-25        1.003338   637.764964      EUR  Payoff      Future
6  2023-01-25        1.003616   211.751181      EUR  Payoff      Future

         date  discountFactor        Price currency   event   occurence
0  2022-01-25        0.000000     0.000000      EUR  Payoff  Historical
1  2022-03-25        1.000123  5617.318231      EUR  Payoff      Future
2  2022-05-25        1.001116  5140.801422      EUR  Payoff      Future
3  2022-07-25        1.002044  4312.135386      EUR  Payoff      Future
4  2022-09-26        1.002831  2084.568546      EUR  Payoff      Future
5  2022-11-25        1.003338   373.426333      EUR  Payoff      Future
6  2023-01-25        1.003616  -383.835241      EUR  Payoff      Future

In [7]:
# Merge all dataframes on the 'date' column
# Add suffix to distinguish between different data sources
combined_df = pd.concat(
    [df_fx.add_suffix('_fx'), 
     df_coupon.add_suffix('_coupon'), 
     df_settlement.add_suffix('_settlement'), 
     df_sum.add_suffix('_sum'), 
     df_alive.add_suffix('_alive'), 
     df_ko_amount.add_suffix('_ko_amount'), 
     df_price.add_suffix('_price')], 
    axis=1
)

# Remove duplicate columns with the same values
combined_df = combined_df.loc[:, ~combined_df.T.duplicated()]

# Keep only one discountFactor column and sort the columns
combined_df = combined_df.loc[:,['date_fx', 'discountFactor_fx', 'FX_fx', 'Coupon_coupon','Settlement_settlement','Sum_sum',  'Alive_alive',
       'KO_Amount_ko_amount','Price_price', 'currency_fx', 'event_fx','occurence_fx']]

# Rename columns to match the desired layout
combined_df.columns = ['date', 'discountFactor', 'FX', 'Coupon', 'Settlement', 'Sum', 'Alive', 'KO_Amount', 'Price', 'currency', 'event', 'occurrence']

# Display the combined dataframe
display(combined_df)

,date,discountFactor,FX,Coupon,Settlement,Sum,Alive,KO_Amount,Price,currency,event,occurrence
0,2022-01-25,0.000000,0.000000,0.000000,0.000000,0.000000,1.0000,0.000000,0.000000,EUR,Payoff,Historical
1,2022-03-25,1.000123,0.906117,0.056117,5611.745667,0.056117,1.0000,0.000000,5617.318231,EUR,Payoff,Future
2,2022-05-25,1.001116,0.904112,0.051360,5136.040150,0.109251,0.9662,292.999264,5140.801422,EUR,Payoff,Future
3,2022-07-25,1.002044,0.901621,0.045418,4541.756301,0.158435,0.7392,1913.796582,4312.135386,EUR,Payoff,Future
4,2022-09-26,1.002831,0.898307,0.040400,4039.973126,0.204555,0.4866,1506.945898,2084.568546,EUR,Payoff,Future
5,2022-11-25,1.003338,0.895248,0.035367,3536.692943,0.247751,0.3428,637.764964,373.426333,EUR,Payoff,Future
6,2023-01-25,1.003616,0.891465,0.029967,2996.714666,0.287477,0.2840,211.751181,-383.835241,EUR,Payoff,Future

##### Greeks

In [8]:
# Extract Greeks from the response
greeks = response.data.analytics[0].greeks

# Convert the dictionary to a DataFrame
df_tarf_greeks = pd.DataFrame(list(greeks.items()), columns=["Greeks", "Value"])

display(df_tarf_greeks)

                 Greeks      Value
0  deltaAmountInDealCcy  1725.7300
1  gammaAmountInDealCcy  -563.4790
2   vegaAmountInDealCcy -1132.2800
3  thetaAmountInDealCcy    73.6331