In [1]:
import os

from moexalgo import session

session.TOKEN = os.environ['APIKEY']
from moexalgo import Market, Ticker

In [2]:
options = Market('options')
options.tickers()

,ticker,board,shortname,secname,prevsettleprice,decimals,minstep,lasttradedate,lastdeldate,latname,...,imtime,buysellfee,scalperfee,negotiatedfee,exercisefee,strike,centralstrike,underlyingasset,underlyingtype,underlyingsettleprice
0,AF4000BL5,ROPD,AFLT-12.25M171225CA4000,Марж. амер. Call 4000 с исп. 17 дек. на фьюч. ...,2084.00,0,1.00,2025-12-17,2025-12-17,AFLT-12.25M171225CA4000,...,2025-09-23 18:59:08,0.48,0.24,0.16,0.26,4000.0,6000.0,AFZ5,F,5915.0
1,AF4000BX5,ROPD,AFLT-12.25M171225PA4000,Марж. амер. Put 4000 с исп. 17 дек. на фьюч. к...,6.00,0,1.00,2025-12-17,2025-12-17,AFLT-12.25M171225PA4000,...,2025-09-23 18:59:08,0.14,0.07,0.14,0.26,4000.0,6000.0,AFZ5,F,5915.0
2,AF4250BC6,ROPD,AFLT-3.26M180326CA4250,Марж. амер. Call 4250 с исп. 18 марта на фьюч....,2075.00,0,1.00,2026-03-18,2026-03-18,AFLT-3.26M180326CA4250,...,2025-09-23 18:59:15,0.50,0.25,0.17,0.28,4250.0,6250.0,AFH6,F,6141.0
3,AF4250BL5,ROPD,AFLT-12.25M171225CA4250,Марж. амер. Call 4250 с исп. 17 дек. на фьюч. ...,1837.00,0,1.00,2025-12-17,2025-12-17,AFLT-12.25M171225CA4250,...,2025-09-23 18:59:08,0.48,0.24,0.16,0.28,4250.0,6000.0,AFZ5,F,5915.0
4,AF4250BO6,ROPD,AFLT-3.26M180326PA4250,Марж. амер. Put 4250 с исп. 18 марта на фьюч. ...,24.00,0,1.00,2026-03-18,2026-03-18,AFLT-3.26M180326PA4250,...,2025-09-23 18:59:15,0.50,0.25,0.17,0.28,4250.0,6250.0,AFH6,F,6141.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29773,YD900CI9,ROPD,YDEXP190929CE900,Прем. европ. Call 900 с исп. 19 сент. на YDEX,3407.11,2,0.01,2029-09-19,2029-09-19,YDEXP190929CE900,...,2025-09-23 18:59:10,0.50,0.25,0.16,0.04,900.0,4100.0,YDEX,S,4075.0
29774,YD900CL9,ROPD,YDEXP191229CE900,Прем. европ. Call 900 с исп. 19 дек. на YDEX,3422.95,2,0.01,2029-12-19,2029-12-19,YDEXP191229CE900,...,2025-09-23 18:59:18,0.50,0.25,0.16,0.04,900.0,4100.0,YDEX,S,4075.0
29775,YD900CR9,ROPD,YDEXP200629PE900,Прем. европ. Put 900 с исп. 20 июня на YDEX,16.34,2,0.01,2029-06-20,2029-06-20,YDEXP200629PE900,...,2025-09-23 18:59:07,0.19,0.10,0.07,0.04,900.0,4100.0,YDEX,S,4075.0
29776,YD900CU9,ROPD,YDEXP190929PE900,Прем. европ. Put 900 с исп. 19 сент. на YDEX,34.52,2,0.01,2029-09-19,2029-09-19,YDEXP190929PE900,...,2025-09-23 18:59:10,0.42,0.21,0.14,0.04,900.0,4100.0,YDEX,S,4075.0
29777,YD900CX9,ROPD,YDEXP191229PE900,Прем. европ. Put 900 с исп. 19 дек. на YDEX,33.52,2,0.01,2029-12-19,2029-12-19,YDEXP191229PE900,...,2025-09-23 18:59:18,0.40,0.20,0.14,0.04,900.0,4100.0,YDEX,S,4075.0

In [3]:
options.marketdata()

,ticker,board,bid,offer,spread,open,high,low,last,quantity,...,offerdeptht,numoffers,time,settletoprevsettleprc,seqnum,systime,oichange,openposition,lasttoprevprice,trade_session_date
0,AF4000BL5,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053646,2025-09-24 05:36:46,0,0,NaN,2025-09-24
1,AF4000BX5,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053646,2025-09-24 05:36:46,0,0,NaN,2025-09-24
2,AF4250BC6,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053636,2025-09-24 05:36:36,0,0,NaN,2025-09-24
3,AF4250BL5,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053646,2025-09-24 05:36:46,0,0,NaN,2025-09-24
4,AF4250BO6,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053703,2025-09-24 05:37:03,0,0,NaN,2025-09-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29773,YD900CI9,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053708,2025-09-24 05:37:08,0,0,NaN,2025-09-24
29774,YD900CL9,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:02,0,20250924053648,2025-09-24 05:36:48,0,0,NaN,2025-09-24
29775,YD900CR9,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053648,2025-09-24 05:36:48,0,0,NaN,2025-09-24
29776,YD900CU9,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:01,0,20250924053643,2025-09-24 05:36:43,0,0,NaN,2025-09-24
29777,YD900CX9,ROPD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,01:43:02,0,20250924053654,2025-09-24 05:36:54,0,0,NaN,2025-09-24

In [4]:
ticker = Ticker('GZ11750BL5')
ticker.info()

,ticker,board,title,board_group_id,market_id,market,engine_id,engine,is_traded,decimals,history_from,history_till,listed_from,listed_till,is_primary,currencyid,unit
0,GZ11750BL5,ROPD,Опционы,35,24,options,4,futures,1,2,2023-06-08,2025-09-23,2023-06-08,2025-09-24,1,None,P

In [5]:
ticker.candles("2025-09-24", "2025-09-24", "10min")

,open,close,high,low,value,volume,begin,end
0,1060,1060,1060,1060,0,4,2025-09-24 10:10:00,2025-09-24 10:19:59
1,1100,1107,1107,1100,0,5,2025-09-24 10:40:00,2025-09-24 10:49:59
2,1077,1077,1077,1077,0,3,2025-09-24 10:50:00,2025-09-24 10:55:03

In [6]:
ticker.trades()

,tradeno,boardname,ticker,tradedate,tradetime,price,quantity,systime,recno,openposition,offmarketdeal,buysell,trade_session_date
0,1896047230175964991,ROPD,GZ11750BL5,2025-09-24,10:14:38,1060,2,2025-09-24 10:14:39,293184558009,4,0,B,2025-09-24
1,1896047230175965051,ROPD,GZ11750BL5,2025-09-24,10:14:47,1060,2,2025-09-24 10:14:48,293184618921,8,0,B,2025-09-24
2,1896047230175969195,ROPD,GZ11750BL5,2025-09-24,10:44:05,1100,4,2025-09-24 10:44:05,293191305417,16,0,B,2025-09-24
3,1896047230175969498,ROPD,GZ11750BL5,2025-09-24,10:48:21,1107,1,2025-09-24 10:48:22,293192085083,16,0,S,2025-09-24
4,1896047230175969842,ROPD,GZ11750BL5,2025-09-24,10:53:21,1077,1,2025-09-24 10:53:21,293192886591,18,0,S,2025-09-24
5,1896047230175969876,ROPD,GZ11750BL5,2025-09-24,10:54:03,1077,2,2025-09-24 10:54:04,293193005803,22,0,S,2025-09-24

In [7]:
ticker.orderbook()

,board,ticker,buysell,price,quantity,seqnum,updatetime,decimals
0,ROPD,GZ11750BL5,B,869,5,20250924110732,11:07:32,0
1,ROPD,GZ11750BL5,B,1050,1,20250924110732,11:07:32,0
2,ROPD,GZ11750BL5,B,1077,3,20250924110732,11:07:32,0
3,ROPD,GZ11750BL5,S,1177,5,20250924110732,11:07:32,0